In [11]:
import pandas as pd
import numpy as np

#lista = [1,2,3,4,5,6]
lista=np.array([1,2,3,4,5])

df = pd.DataFrame({'coluna1':lista})

In [6]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df

coluna1
0        1
1        2
2        3
3        4
4        5

In [15]:
type(df.coluna1)

pandas.core.series.Series

In [22]:
lista=np.array([1,2,3,4,5])
lista[2:]

array([3, 4, 5])

In [43]:
x2 = np.array([1,2,3])

x3 = np.array([[1],
               [2],
               [3]])

x4 = np.array([[1,2,3],
               [1,2,3],
               [1,2,3]])

In [28]:
x3+x2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [44]:
x3+x4

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [32]:
x4*2
x4+x4

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

In [37]:
x5 = np.array([[1],[2]])

In [38]:
x5+x4

ValueError: operands could not be broadcast together with shapes (2,1) (3,3) 